version: "3.9"
services:
  mongo:
    image: mongo
    container_name: seeksi-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: seeksi
    volumes:
      - data-volume:/data/db
      - ./scripts/db:/scripts
      - ./scripts/db/init:/docker-entrypoint-initdb.d
    networks:
      - seeksi-network
  dashboard:
    image: mongo-express
    container_name: mongo-dashboard
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: seeksi-db
    depends_on:
      - mongo
    networks:
      - seeksi-network
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: seeksi-server
    ports:
      - "4000:4000"
    environment:
      MONGODB_CONNECTION: mongodb://mongo:27017/seeksi
      SALT_ROUND:
      TOKEN_SIZE:
      JWT_SECRET:
      JWT_EXPIRE_IN:
      SENDGRID_API_KEY:
      SENDGRID_EMAIL:
      PASSWORD_RESET_TEMPLATE_ID:
      ACCOUNT_DEACTIVATION_TEMPLATE_ID:
      CLOUDINARY_CLOUD_NAME:
      CLOUDINARY_API_KEY:
      CLOUDINARY_API_SECRET:
      MAX_IMAGE_UPLOAD:
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - seeksi-network
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: seeksi-client
    ports:
      - "3000:3000"
    environment:
      REACT_APP_GRAPHQL_URI: http://localhost:4000
      REACT_APP_STATUS_EXPIRE_AFTER: 60
      REACT_APP_STATUS_UPDATE_AFTER: 30
      REACT_APP_GET_STATUS_AFTER: 10
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - seeksi-network
networks:
  seeksi-network:
    driver: bridge
volumes:
  data-volume:
